# Loki Tilt Extension
# Provides Loki log aggregation system.
#
# Exports:
#   cc_export()    - Returns plugin struct for compose_composer

load('ext://compose_composer', 'cc_init')

cc = cc_init('loki')

def cc_export():
    """Returns the plugin struct for compose_composer."""
    return cc.create(
        'loki',
        os.path.dirname(__file__) + '/loki.yaml',
        labels=['observability'],
    )

