# MS SQL Server Test Tilt Extension
# Provides MS SQL Server test database for SQL testing.
#
# Exports:
#   cc_export()    - Returns plugin struct for compose_composer

load('ext://compose_composer', 'cc_init')

cc = cc_init('mssql-test')

def cc_export():
    """Returns the plugin struct for compose_composer."""
    return cc.create(
        'mssql-test',
        os.path.dirname(__file__) + '/mssql-test.yaml',
        labels=['sql-test'],
    )
