# BigQuery Emulator Tilt Extension
# Provides BigQuery emulator for SQL testing.
#
# Exports:
#   cc_export()    - Returns plugin struct for compose_composer

load('ext://compose_composer', 'cc_init')

cc = cc_init('bigquery-emulator')

def cc_export():
    """Returns the plugin struct for compose_composer."""
    return cc.create(
        'bigquery-emulator',
        os.path.dirname(__file__) + '/bigquery-emulator.yaml',
        labels=['sql-test'],
    )
